export const mockInput = [
  {
    'identification.typeOfDeath': 'Não fetal',
    'identification.dateOfDeath': '2024-10-05',
    'identification.hourOfDeath': '14:30',
    'identification.deceasedName': 'João da Silva',
    'identification.mothersName': 'Maria da Silva',
    'identification.fathersName': 'José da Silva',
    'identification.naturalness': 'São Paulo',
    'identification.dateOfBirth': '1980-05-20',
    'identification.age': '44',
    'identification.sex': 'M',
    race: 'Branca',
    maritalStatus: 'Casado(a)',
    susCard: '123456789',
    education: 'Superior completo',
    class: 'Classe A',
    occupation: 'Engenheiro',
    cbo: '214101',
    deceasedAddress: {
      zipCode: '01001-000',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
      street: 'Rua das Flores',
    },
    occurrence: {
      address: {
        zipCode: '01002-000',
        number: '456',
        neighborhood: 'Bela Vista',
        city: 'São Paulo',
        state: 'SP',
        street: 'Avenida Paulista',
      },
      cnes: '1234567',
      establishmentName: 'Hospital São Paulo',
      hospitalAddress: {
        zipCode: '01003-000',
        number: '789',
        neighborhood: 'Liberdade',
        city: 'São Paulo',
        state: 'SP',
        street: 'Rua Vergueiro',
      },
      placeType: 'Hospital',
    },
    infant: {
      mothersAge: '30',
      mothersEducation: 'Médio (antigo 2º grau)',
      mothersClass: 'Classe B',
      mothersOccupation: 'Professora',
      bornAlive: true,
      fetalLoss: 'Não',
      weeksPregnant: '38',
      pregnancyType: 'Única',
      birthType: 'Cesárea',
      birthWeight: '3200',
      deathRelativeToBirth: 'Imediatamente após',
      birthCertificateNumber: '987654321',
    },
    conditions: {
      fertileAgeDeath: 'Sim',
      receivedMedicalAssistance: 'Sim',
      necropsy: 'Sim',
      cause1: 'Infarto',
      evolutionTime1: '2 horas',
      cid1: 'I21.9',
      cause2: 'Insuficiência Respiratória',
      evolutionTime2: '30 minutos',
      cid2: 'J96.0',
    },
    doctor: {
      name: 'Dr. Roberto Mendes',
      crm: '123456-SP',
      confirmedBy: 'Assistente',
      city: 'São Paulo',
      contact: '11987654321',
      confirmationDate: '2024-10-06',
    },
    external: {
      nonNaturalType: 'Acidente',
      workplaceAccident: 'Não',
      informationSource: 'Hospital',
      placeType: 'Via pública',
      occurrenceNumber: '789123',
      occurrenceDescription: 'Acidente de carro',
      occurrenceAddress: {
        zipCode: '01004-000',
        number: '101',
        neighborhood: 'Sé',
        city: 'São Paulo',
        state: 'SP',
        street: 'Rua da Consolação',
      },
    },
  },
];
